In [12]:
import numpy as np
l = [i for i in range(1,11)]
# print(l)
arr = np.array(l,dtype=np.uint32)
print("array : ",arr)
print("array shape: ", arr.shape)
print("array dim: ",arr.ndim)
print("array size: ",arr.size)
print("array type: ",arr.dtype)
print("array itemsize: ", arr.itemsize)
print("array nbytes: ", arr.nbytes)
# print(help(arr))

array :  [ 1  2  3  4  5  6  7  8  9 10]
array shape:  (10,)
array dim:  1
array size:  10
array type:  uint32
array itemsize:  4
array nbytes:  40


In [19]:
import numpy as np
l = [ i for i in range(1,11)]
# print(l)
arr = np.array(l,dtype=np.uint16)
print("array: ",arr)
print("array size: ", arr.size)
print("array shape: ",arr.shape)
print("array dim: ", arr.ndim)
print("array type: ", arr.dtype)
print("array itemsize: ", arr.itemsize)
print("array nbytes: ", arr.nbytes)

array:  [ 1  2  3  4  5  6  7  8  9 10]
array size:  10
array shape:  (10,)
array dim:  1
array type:  uint16
array itemsize:  2
array nbytes:  20


In [23]:
import numpy as np
l = [[i for i in range(j,j+3)] for j in range(1,4)]
print(l)

[[1, 2, 3], [2, 3, 4], [3, 4, 5]]


In [25]:
import numpy as np
# np.zeros(shape, dtype=float)
arr = np.zeros(3)
print(arr)

[0. 0. 0.]


In [26]:
import numpy as np
arr = np.zeros((2,3), dtype=np.uint16)
print(arr)

[[0 0 0]
 [0 0 0]]


In [27]:
import numpy as np
arr = np.ones(3)
print(arr)

[1. 1. 1.]


In [29]:
import numpy as np
arr = np.ones((3,3), dtype=np.uint16)
print("array shape: ", arr.shape)
print("array itemsize: ", arr.itemsize)
print("array ndim: ", arr.ndim)
print("array size: ", arr.size)
print("array nbytes: ", arr.nbytes)
print("array dtype: ", arr.dtype)

array shape:  (3, 3)
array itemsize:  2
array ndim:  2
array size:  9
array nbytes:  18
array dtype:  uint16


In [ ]:
import numpy as np